### PR TITLE
GraphARM. Use of initial diffusion trajectories for whole learning step

### PR DESCRIPTION
**Pull request by JoseAndresMR**

### CODE REVIEW

**Comment by JoseAndresMR** [comment]
I am getting an error when starting the diffusion ordering network training part. You can take a look.

**Comment by caio-freitas** [comment]
I had no troubles running the the training on your branch. Could you post here what you're getting?

**Comment by JoseAndresMR** [comment]
Oh, that's a surprise. This is my outcome.

Screenshot from 2024-01-20 13-17-27

**Comment by caio-freitas** [comment]
Maybe checking the versions of your packages, specially `torch_geometric`, what I have here is `2.3.1`. But also, looks like that would be solved adding a `retain_graph=True` in the `.backwards()` function.

**Comment by JoseAndresMR** [comment]
Yes, it worked but I was not sure it would be a good solution. Anyways, it seems that the second fix is completed. Only one left!

**Review by caio-freitas — APPROVED** [review]

**Pull request merged**
